"""baseline Phase 1-5 schema

Revision ID: cd2aba0d4cab
Revises: 
Create Date: 2026-09-17 18:15:04.938210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database


revision: str = 'cd2aba0d4cab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_nonces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_nonces_agent_id'), 'auth_nonces', ['agent_id'], unique=False)
    op.create_index(op.f('ix_auth_nonces_nonce'), 'auth_nonces', ['nonce'], unique=True)
    op.create_table('bounded_authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorization_id', sa.String(length=64), nullable=False),
    sa.Column('intent_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=False),
    sa.Column('amount_minor_units', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('issued_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('max_usage', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bounded_authorizations_agent_id'), 'bounded_authorizations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_bounded_authorizations_authorization_id'), 'bounded_authorizations', ['authorization_id'], unique=True)
    op.create_index(op.f('ix_bounded_authorizations_intent_id'), 'bounded_authorizations', ['intent_id'], unique=False)
    op.create_table('mfa_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.String(length=64), nullable=False),
    sa.Column('intent_id', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfa_challenges_challenge_id'), 'mfa_challenges', ['challenge_id'], unique=True)
    op.create_index(op.f('ix_mfa_challenges_intent_id'), 'mfa_challenges', ['intent_id'], unique=False)
    op.create_table('parent_authorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('parent_type', sa.String(length=50), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('public_key_pem', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.Enum('PENDING_VERIFICATION', 'ACTIVE', 'REJECTED', 'REVOKED', name='parentstatus'), nullable=False),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('verified_at', app.database.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_authorities_parent_id'), 'parent_authorities', ['parent_id'], unique=True)
    op.create_table('payment_intents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intent_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=False),
    sa.Column('amount_minor_units', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('decision', sa.Enum('ALLOW', 'REVIEW', 'DENY', name='governancedecision'), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('mfa_required', sa.Boolean(), nullable=False),
    sa.Column('mfa_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'idempotency_key', name='uq_payment_intents_agent_idem')
    )
    op.create_index(op.f('ix_payment_intents_agent_id'), 'payment_intents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_payment_intents_idempotency_key'), 'payment_intents', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_payment_intents_intent_id'), 'payment_intents', ['intent_id'], unique=True)
    op.create_index(op.f('ix_payment_intents_transaction_id'), 'payment_intents', ['transaction_id'], unique=False)
    op.create_table('provider_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authorization_id', sa.String(length=64), nullable=False),
    sa.Column('intent_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('webhook_event_id', sa.String(length=100), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id'),
    sa.UniqueConstraint('webhook_event_id')
    )
    op.create_index(op.f('ix_provider_transactions_agent_id'), 'provider_transactions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_provider_transactions_authorization_id'), 'provider_transactions', ['authorization_id'], unique=True)
    op.create_index(op.f('ix_provider_transactions_intent_id'), 'provider_transactions', ['intent_id'], unique=False)
    op.create_table('revocation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revocation_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('consumed_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revocation_records_agent_id'), 'revocation_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_revocation_records_revocation_id'), 'revocation_records', ['revocation_id'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('parent_pk', sa.Integer(), nullable=False),
    sa.Column('delegation_id', sa.String(length=64), nullable=False),
    sa.Column('public_key_pem', sa.String(length=2000), nullable=False),
    sa.Column('granted_capabilities', sa.JSON(), nullable=False),
    sa.Column('payment_limit_minor_units', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REVOKED', name='agentstatus'), nullable=False),
    sa.Column('created_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_until', app.database.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_pk'], ['parent_authorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=True)
    op.create_table('delegation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delegation_id', sa.String(length=64), nullable=False),
    sa.Column('parent_pk', sa.Integer(), nullable=False),
    sa.Column('agent_public_key_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('granted_capabilities', sa.JSON(), nullable=False),
    sa.Column('payment_limit_minor_units', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('issued_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('consumed_at', app.database.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_pk'], ['parent_authorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegation_records_delegation_id'), 'delegation_records', ['delegation_id'], unique=True)
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=64), nullable=False),
    sa.Column('agent_pk', sa.Integer(), nullable=False),
    sa.Column('signed_jwt', sa.String(length=4000), nullable=False),
    sa.Column('issued_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_pk'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_credential_id'), 'credentials', ['credential_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credentials_credential_id'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_delegation_records_delegation_id'), table_name='delegation_records')
    op.drop_table('delegation_records')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_revocation_records_revocation_id'), table_name='revocation_records')
    op.drop_index(op.f('ix_revocation_records_agent_id'), table_name='revocation_records')
    op.drop_table('revocation_records')
    op.drop_index(op.f('ix_provider_transactions_intent_id'), table_name='provider_transactions')
    op.drop_index(op.f('ix_provider_transactions_authorization_id'), table_name='provider_transactions')
    op.drop_index(op.f('ix_provider_transactions_agent_id'), table_name='provider_transactions')
    op.drop_table('provider_transactions')
    op.drop_index(op.f('ix_payment_intents_transaction_id'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_intent_id'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_idempotency_key'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_agent_id'), table_name='payment_intents')
    op.drop_table('payment_intents')
    op.drop_index(op.f('ix_parent_authorities_parent_id'), table_name='parent_authorities')
    op.drop_table('parent_authorities')
    op.drop_index(op.f('ix_mfa_challenges_intent_id'), table_name='mfa_challenges')
    op.drop_index(op.f('ix_mfa_challenges_challenge_id'), table_name='mfa_challenges')
    op.drop_table('mfa_challenges')
    op.drop_index(op.f('ix_bounded_authorizations_intent_id'), table_name='bounded_authorizations')
    op.drop_index(op.f('ix_bounded_authorizations_authorization_id'), table_name='bounded_authorizations')
    op.drop_index(op.f('ix_bounded_authorizations_agent_id'), table_name='bounded_authorizations')
    op.drop_table('bounded_authorizations')
    op.drop_index(op.f('ix_auth_nonces_nonce'), table_name='auth_nonces')
    op.drop_index(op.f('ix_auth_nonces_agent_id'), table_name='auth_nonces')
    op.drop_table('auth_nonces')
    # ### end Alembic commands ###
